# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170212_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product_five',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product_5', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product_four',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product_4', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product_one',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product_1', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product_six',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product_6', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product_three',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product_3', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product_2', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_product_type',
            field=models.CharField(choices=[('0', 'Price'), ('1', 'Manual'), ('2', 'Characteristics'), ('3', 'Apriori')], default='1', max_length=1),
        ),
    ]
