# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170521_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent_product_one',
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product_one',
            field=models.ManyToManyField(related_name='_product_parent_product_one_+', to='products.Product'),
        ),
    ]
